# Generated by Django 4.2 on 2023-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=1000, verbose_name='имя')),
                ('telegram_id', models.CharField(max_length=20, verbose_name='телеграм айди')),
                ('group_number', models.CharField(blank=True, max_length=5, verbose_name='номер группы')),
            ],
        ),
    ]
