# Generated by Django 3.1.2 on 2023-12-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20231215_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='first_name',
            new_name='title_group',
        ),
    ]
